# Generated by Django 5.2.1 on 2025-05-26 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "date_of_death",
                    models.DateField(blank=True, null=True, verbose_name="Retired"),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.RemoveField(
            model_name="bookinstance",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookinstance",
            name="borrower",
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Enter a brew genre (e.g. Stout, Green Tea, Espresso)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                help_text="Enter the language of the brew", max_length=200
            ),
        ),
        migrations.CreateModel(
            name="Brew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.TextField(
                        help_text="Enter a brief description of the brew",
                        max_length=1000,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the brew",
                        max_length=13,
                        unique=True,
                        verbose_name="Brew Code",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        help_text="Select a genre for this brew", to="catalog.genre"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Select a language for this brew",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.language",
                    ),
                ),
                (
                    "brewer",
                    models.ManyToManyField(
                        help_text="Enter a brew brewer", to="catalog.brewer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrewInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this particular brew tasting",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("imprint", models.CharField(max_length=200)),
                ("due_back", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m", "Maintenance"),
                            ("o", "On tasting"),
                            ("a", "Available"),
                            ("r", "Reserved"),
                        ],
                        default="m",
                        help_text="Brew tasting availability",
                        max_length=1,
                    ),
                ),
                (
                    "brew",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalog.brew",
                    ),
                ),
                (
                    "taster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set brew as returned"),),
            },
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="BookInstance",
        ),
    ]
