# Generated by Django 5.2.1 on 2025-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_brewer_remove_book_author_remove_book_genre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrewType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a brew brewType (e.g. Stout, Green Tea, Espresso)",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="brew",
            name="genre",
        ),
        migrations.AddField(
            model_name="brew",
            name="brewType",
            field=models.ManyToManyField(
                help_text="Select a brewType for this brew", to="catalog.brewtype"
            ),
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
